export default interface unformattedData {
address: string
city: string,
company0?: string,
company1?: string,
company2?: string,
company3?: string,
company4?: string,
course1?: string,
course2?: string,
course3?: string,
course4?: string,
courseDate1?: string,
courseDate2?: string,
courseDate3?: string,
courseDate4?: string,
dateofbirth: string,
degree0?: string,
degree1?: string
degree2?: string
degree3?: string
description: string,
email: string,
language0?: string,
language1?: string,
language2?: string,
language3?: string,
languageSkill0?: string,
languageSkill1?: string,
languageSkill2?: string,
languageSkill3?: string,
name: string,
orientation0?: string,
orientation1?:string,
orientation2?:string,
orientation3?:string,
postcode: string,
reference0?: string,
reference1?: string,
reference2?: string,
reference3?: string,
referenceContact0?: string,
referenceContact1?: string,
referenceContact2?: string,
referenceContact3?: string,
role0?: string,
role1?: string,
role2?: string,
role3?: string,
role4?: string,
school0?: string,
school1?: string,
school2?: string,
school3?: string,
studyDate0?: string,
studyDate1?: string,
studyDate2?: string,
studyDate3?: string,
telephone: string,
workingDate0?: string,
workingDate1?: string,
workingDate2?: string,
workingDate3?: string,
workingDate4?: string,
workingExperience0?:string,
workingExperience1?:string,
workingExperience2?:string,
workingExperience3?:string,
}